FROM xyez/python3.8-torch1.8.2-cuda11.1:local0
RUN pip3 --no-cache-dir install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html && \
    pip3 --no-cache-dir install --upgrade enum34 tensorboard \
    tensorflow-gpu \
    # EfficientZero
    kornia && \
    sudo apt-get clean && \
    sudo apt-get autoremove && \
    sudo rm -rf /var/lib/apt/lists/* /tmp/*pip3 --no-cache-dir install --upgrade \
    ray 'ray[default]' 'ray[data]' dask 'ray[tune]' 'ray[serve]' scikit-learn 'ray[rllib]' && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/*
CMD [ "zsh" ]
#ENTRYPOINT ["/entrypoint.sh"]