FROM docker.kt.io/rlg1/yaoxin/ubuntu22.04:base-v3
RUN mv /usr/local/bin/jupyter-server /usr/local/bin/jupyter-server.bak && \
    echo '#!/bin/bash' > /usr/local/bin/jupyter-server && \
    echo 'su docker -c /usr/local/bin/jupyter-server' >> /usr/local/bin/jupyter-server && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/*
EXPOSE 8888
# xyez/python3.8-cuda11.3:torch1.11
#ENTRYPOINT ["/entrypoint.sh"]
