FROM nvidia/cuda:11.3.0-cudnn8-devel-ubuntu18.04
RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    rm /etc/apt/sources.list.d/* && \
    # curl -s -L https://nvidia.github.io/libnvidia-container/gpgkey | apt-key add - && \
# install necessary
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && \
    apt-get update && apt-get install -y software-properties-common apt-utils wget apt-transport-https && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    qt5-default \
    python2.7 python2.7-dev python-pip && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3.8 python3.8-dev python3.8-tk python3-distutils-extra && \
    ln -s /usr/bin/python3.8-config /usr/local/bin/python3-config && \
    ln -s /usr/bin/python3.8 /usr/local/bin/python3 && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/*
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    # python2 packaeg
    python-numpy \
    python-dev \
    python-opengl \
    python-opencv \
    # PIL
    libfreetype6-dev \
    # opencv
    libjpeg-dev \
    libgtk2.0-dev \
    # zmq
    libzmq3-dev \
    # useful
    aptitude \
    pkg-config \
    build-essential ca-certificates \
    net-tools \
    sudo ssh curl expect openssh-server \
    cmake \
    locales htop vim git tmux ffmpeg \
    ttf-wqy-zenhei \
    qtbase5-dev \
    libfuse2 \
    fuse \
    libnss3 \
    zsh \
    iptables firewalld \
    mplayer iputils-ping \
    # project
    openssl1.0 libboost-program-options1.62.0 libboost-filesystem1.62.0 \
    # xclock
    x11-apps mesa-utils \
    # pciture and pdf viewer
    evince eog \
    zip rar unzip unrar p7zip-full p7zip-rar \
    rsync pigz tree \
    parallel \
    # mujoco render
    libglfw3 libglfw3-dev libglew-dev libgl1-mesa-glx libosmesa6-dev \
    # mujoco
    patchelf \
    libgl1-mesa-dev libopenmpi-dev zlib1g-dev libpcre16-3 libsm6 libxext6 libxrender-dev \
    # unknow
    libxslt1.1 \
    libffi-dev \
    xserver-xorg-dev \
    libcanberra-gtk-module \
    xvfb \
    xorg-dev \ 
    libtinyxml-dev \
    # go
    golang \
    # c++?
    swig \
    # ???
    libboost-all-dev \
    libsdl2-dev \
    libassimp-dev \
    libboost-python-dev \
    # dns tools
    dnsutils \
    # no use
    # terminator \
    # desktop
    # xpra \
    # feedgnuplot \
    && \
#    language
    locale-gen en_US.UTF-8 zh_CN.UTF-8 && \
    # sed -i '$a\LANG="en_US.UTF-8"\nLC_CTYPE="en_US.UTF-8"\nLC_NUMERIC="zh_CN.UTF-8"\nLC_TIME="zh_CN.UTF-8"\nLC_COLLATE="en_US.UTF-8"\nLC_MONETARY="zh_CN.UTF-8"\nLC_MESSAGES="en_US.UTF-8"\nLC_PAPER="zh_CN.UTF-8"\nLC_NAME="zh_CN.UTF-8"\nLC_ADDRESS="zh_CN.UTF-8"\nLC_TELEPHONE="zh_CN.UTF-8"\nLC_MEASUREMENT="zh_CN.UTF-8"\nLC_IDENTIFICATION="zh_CN.UTF-8"' /etc/default/locale && \
    # config ssh
#    sed -i 's/.*PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
#    ldconfig && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/*
