FROM xyez/python3.8-cuda11.3:torch1.11
RUN USER=docker && \
    GROUP=docker && \
    LOCALHOST=http://127.0.0.1:8000 && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    dnsutils && \
    wget $LOCALHOST/zshrc -O /home/$USER/.zshrc && \
    chown -R $USER:$USER /home/$USER && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/*
#ENTRYPOINT ["/entrypoint.sh"]
