FROM xyez/python3.8-cuda11.3:pip0
RUN USER=docker && \
    GROUP=docker && \
    LOCALHOST=http://127.0.0.1:8000 && \
#   add user
    addgroup --gid 999999 $GROUP && \
    useradd --uid 999999 -g $GROUP -ms /bin/zsh $USER && \
    adduser $USER sudo && \
#   install zsh
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" && \
#   set zsh default
    sed -i "s/bash/zsh/g" /etc/passwd && \
#   set sudo no passwd
    sed --in-place '26,$s/ALL$/NOPASSWD: ALL/' /etc/sudoers && \
#   set sshd
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config && \
    sed -i '/X11Forwarding yes/aX11UseLocalhost no' /etc/ssh/sshd_config && \
#   fixuid
    # wget https://github.com/boxboat/fixuid/releases/download/v0.5/fixuid-0.5-linux-amd64.tar.gz && \
    wget $LOCALHOST/fixuid-0.5-linux-amd64.tar.gz && \
    tar zxf ./fixuid-0.5-linux-amd64.tar.gz && \
    mv fixuid /usr/local/bin/fixuid && \
    rm ./fixuid-0.5-linux-amd64.tar.gz && \
    chown root:root /usr/local/bin/fixuid && \
    chmod 4755 /usr/local/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    printf "user: $USER\ngroup: $GROUP\npaths:\n  - /home/$USER" > /etc/fixuid/config.yml && \
    printf "#!/bin/bash\nvar=\$(ls -nd \$1)\ntheuid=\`echo \$var|awk '{print \$3}'\`\nthegid=\`echo \$var|awk '{print \$4}'\`\nusermod -u \$theuid docker\nusermod -g 0 docker\ndelgroup docker\naddgroup --gid \$thegid docker\nusermod -g \$thegid docker\nchown -R docker:docker /home/docker" > /usr/local/bin/fixids && \
    chmod +x /usr/local/bin/fixids && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/*
USER docker:docker
RUN USER=docker && \
    LOCALHOST=http://127.0.0.1:8000 && \
    cd /home/$USER/ && \
    mkdir -p /home/$USER/.config /home/$USER/.local/bin && \
    sudo cp -r /root/.config/pip /home/$USER/.config/pip && \
    sudo cp -r /root/.oh-my-zsh /home/$USER/.oh-my-zsh && \
    wget $LOCALHOST/zshrc -O /home/$USER/.zshrc && \
    wget $LOCALHOST/tmux.conf -O /home/$USER/.tmux.conf && \
    sudo chown -R $USER:$USER /home/$USER && \
#   for mujoco
    mkdir -p /home/$USER/.mujoco && \
    cd /home/$USER/.mujoco && \
    wget https://www.roboti.us/download/mujoco200_linux.zip && \
    unzip mujoco200_linux.zip && \
    mv mujoco200_linux mujoco200 && \
    rm mujoco200_linux.zip && \
    wget $LOCALHOST/mjkey.txt -P /home/$USER/.mujoco && \
#   mujoco dependency
    # pip3 --no-cache-dir install --upgrade pyproject.toml && \
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.mujoco/mujoco200/bin pip3 --no-cache-dir install --upgrade mujoco-py==2.0.2.13 && \
    wget $LOCALHOST/dmc2gym-master.zip && sudo pip3 --no-cache-dir install dmc2gym-master.zip && rm dmc2gym-master.zip && \
    wget $LOCALHOST/metaworld-master.zip && sudo pip3 --no-cache-dir install metaworld-master.zip && rm metaworld-master.zip && \
    wget $LOCALHOST/smac-master.zip && sudo pip3 --no-cache-dir install smac-master.zip && rm smac-master.zip && \
    #sudo pip3 --no-cache-dir install git+git://github.com/denisyarats/dmc2gym.git && \
    #sudo pip3 --no-cache-dir install git+https://github.com.cnpmjs.org/rlworkgroup/metaworld.git@master#egg=metaworld && \
    #sudo pip3 --no-cache-dir install git+https://github.com/oxwhirl/smac.git && \
#   for zsh plugins
    wget -qO- $LOCALHOST/zsh-syntax-highlighting.tar | tar xf - && \
    wget -qO- $LOCALHOST/zsh-autosuggestions.tar | tar xf -  && \
    wget -qO- $LOCALHOST/zsh-completions.tar | tar xf -  && \
    mv zsh-syntax-highlighting ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting && \
    mv zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
    mv zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions && \
    # git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting && \
    # git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
    # git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions && \
#   install others
    # sudo apt-get update && \
    # sudo DEBIAN_FRONTEND=noninteractive apt-get install -y evince eog && \
    sudo apt-get clean && \
    sudo apt-get autoremove && \
    sudo rm -rf /var/lib/apt/lists/* /tmp/*
USER root:root

