FROM xyez/python3.8-cuda11.3:apt0
ENV LANG="en_US.UTF-8" LC_CTYPE="en_US.UTF-8" LC_NUMERIC="zh_CN.UTF-8" LC_TIME="zh_CN.UTF-8" LC_COLLATE="en_US.UTF-8" LC_MONETARY="zh_CN.UTF-8" LC_MESSAGES="en_US.UTF-8" LC_PAPER="zh_CN.UTF-8" LC_NAME="zh_CN.UTF-8" LC_ADDRESS="zh_CN.UTF-8" LC_TELEPHONE="zh_CN.UTF-8" LC_MEASUREMENT="zh_CN.UTF-8" LC_IDENTIFICATION="zh_CN.UTF-8"
RUN wget -O ~/get-pip.py https://bootstrap.pypa.io/get-pip.py && \
#    wget -O ~/get-pip.py https://bootstrap.pypa.io/get-pip.py && \
    python3.8 ~/get-pip.py && \
    rm ~/get-pip.py && \
    python3 -m pip install pip -U && \
    # pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple && \
    pip3 config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple && \
    pip3 install --upgrade pip && \
    pip3 --no-cache-dir install --upgrade \
    	# base
        setuptools \
        numpy \
        scipy \
        pandas \
        cloudpickle \
        scikit-learn \
        matplotlib \
        opencv-python \
        Cython \
        ranger-fm \
        scikit-image plotly jupyter ipykernel jupyterlab sklearn Pillow \
        seaborn \
        # dependency
        PyQt5 \
        # rl
        gym==0.19.0 \
        atari_py==0.2.6 \
        # gym[atari] 
        roboschool stable-baselines \
        dm_control \
        mpi4py \
        # tools
        zmqnumpy \
        pyftpdlib \
        tmuxp \
        tqdm \
        pyopengl \
        typing \
        pyyaml \
        protobuf \
        visdom \
        future \
        # others
        empy \
        ipdb \
        imageio \
        jsonpickle \
        gtimer \
        path.py \
        cached-property \
        flask \
        joblib \
        six \
        hydra-core \
        pyprind \
        virtualenv glog psutil pgrep \
        glfw imageio pycparser cffi lockfile absl-py && \
    rm -rf /var/lib/apt/lists/* /tmp/*
